version: "3.7"
services:
  app:
    container_name: liikunta-helsinki
    build:
      context: .
      target: ${DOCKER_TARGET:-production}
    ports:
      - "3000:3000"
    env_file:
      - .env.local
